app3_employee_management/urls.py
from django.urls import path
from .views import EmployeeAdd, EmployeeDelete, EmployeeEdit, EmployeeDocumentsAdd, EmployeeDocumentsDelete, EmployeeSearchView, EmployeeFilterView
app_name = 'app3_employee_management'
urlpatterns = [
    path('employee_management/add_employee',EmployeeAdd.as_view(),name="add_employee"),
    path('employee_management/employee_delete/<str:u_id>',EmployeeDelete.as_view(),name="employee_delete"),
    path('employee_management/edit_employee/<str:u_id>',EmployeeEdit.as_view(),name="edit_employee"),
    path('employee_management/employee_documents/<str:u_id>',EmployeeDocumentsAdd.as_view(),name="employee_documents"),
    path('employee_management/employee_document_delete/<str:d_id>',EmployeeDocumentsDelete.as_view(),name="employee_document_delete"),
    path('employee_management/employee_search',EmployeeSearchView.as_view(),name="employee_search"),
    path('employee_management/employee_filter/<str:filter_name>',EmployeeFilterView.as_view(),name="employee_filter"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1_authentication.urls')),
    path('auth/',include('app1_authentication.urls')),
    path('user_manage/',include('app1_authentication.urls')),
    path('admin_dashboard/',include('app2_admin_dashboard.urls')),
    path('employee_manage/',include('app3_employee_management.urls')),
    path('product_manage/',include('app4_product.urls')),
    path('raw_materials/',include('app5_raw_materials.urls')),
    path('master_data/',include('app6_master.urls')),
    path('rms/',include('app7_rms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app3_employee_management/models.py
from django.db import models
from django.contrib import admin
from app6_master.models import Designation
# Create your models here.
class Employee(models.Model):
 
    name=models.CharField(max_length=255,null=True,blank=True)
    address=models.TextField(null=True,blank=True)
    contact1=models.CharField(max_length=255,null=True,blank=True)
    contact2=models.CharField(max_length=255,null=True,blank=True)
    email=models.EmailField(null=True,blank=True)

    profile_pic=models.ImageField(upload_to="employee_images/",null=True,blank=True)

    date_of_joining=models.CharField(max_length=255,null=True,blank=True)
    date_of_leaving=models.CharField(max_length=255,null=True,blank=True)

    addhar_number=models.CharField(max_length=255,null=True,blank=True)
    driving_lisence=models.CharField(max_length=255,null=True,blank=True)
    pan_card=models.CharField(max_length=255,null=True,blank=True)

    bank_ac_number=models.CharField(max_length=255,null=True,blank=True)
    ifsc_code=models.CharField(max_length=255,null=True,blank=True)

    working_hour=models.CharField(max_length=255,null=True,blank=True)
    basic_salary=models.FloatField(default=0.0)
    extra_money=models.FloatField(default=0.0)
    advance=models.FloatField(default=0.0)
    designation=models.ForeignKey(Designation,on_delete=models.SET_NULL,null=True,blank=True)
    locker_number=models.CharField(max_length=255,null=True,blank=True)

    is_active=models.BooleanField(default=True)
    extra_info=models.TextField(null=True,blank=True)

admin.site.register(Employee)

class EmployeeDocuments(models.Model):
    name=models.CharField(max_length=255,null=True,blank=True)
    file_data=models.FileField(upload_to='employee_documents/',null=True,blank=True)
    employee=models.ForeignKey(Employee, on_delete=models.CASCADE, null=True,blank=True)

admin.site.register(EmployeeDocuments)

app3_employee_management/forms.py
from django import forms
from .models import Employee, EmployeeDocuments
from app6_master.models import Designation
 
class EmployeeCreationForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields='__all__'
        #exclude = ['designation']
    name=forms.CharField(required=True)
    address=forms.CharField(required=True)
    contact1=forms.IntegerField(required=True)
    contact2=forms.IntegerField()
    email=forms.EmailField()

    date_of_joining=forms.CharField(required=True)
    date_of_leaving=forms.CharField()

    addhar_number=forms.CharField(required=True)
    driving_lisence=forms.CharField(required=True)
    pan_card=forms.CharField(required=True)

    bank_ac_number=forms.CharField(required=True)
    ifsc_code=forms.CharField(required=True)

    working_hour=forms.CharField(required=True)
    basic_salary=forms.FloatField(required=True)
    extra_money=forms.FloatField(required=True)
    advance=forms.FloatField(required=True)
    designation=forms.ModelChoiceField(queryset=Designation.objects.all())
    locker_number=forms.CharField(required=True)
    extra_info=forms.CharField(required=True)

    name.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Name',"required":"required"})
    address.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Address',"required":"required"})
    contact1.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'Enter Contact1',"required":"required"})
    contact2.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'Enter Contact2'})
    email.widget.attrs.update({'class': 'form-control','type':'email','placeholder':'Enter Contact2'})

    date_of_joining.widget.attrs.update({'class': 'form-control','data-datepicker':'','type':'text','id':'birthday','placeholder':'dd/mm/yyyy'})
    date_of_leaving.widget.attrs.update({'class': 'form-control','data-datepicker':'','type':'text','id':'birthday','placeholder':'dd/mm/yyyy'})

    addhar_number.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Aadhaar Number',"required":"required"})
    driving_lisence.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Driving Lisence'})
    pan_card.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Pan-card Number'})

    bank_ac_number.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Bank Account Number'})
    ifsc_code.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter IFSC Code'})

    working_hour.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'Enter Working Hour',"required":"required"})
    basic_salary.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'Enter Basic Salary',"required":"required"})
    extra_money.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'If getting Extra allowence'})
    advance.widget.attrs.update({'class': 'form-control','type':'number','placeholder':'If any Advance money'})
    designation.widget.attrs.update({'class': 'form-control','type':'text',"required":"required"})
    locker_number.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Loker Number',"required":"required"})
    extra_info.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Extra Information'})

class EmployeeDocumentForm(forms.ModelForm):
    class Meta:
        model=EmployeeDocuments
        fields=['name','file_data']
    name=forms.CharField(required=True)

    name.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Document Name'})

app3_employee_management/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from .forms import EmployeeCreationForm, EmployeeDocumentForm
from .models import Employee, EmployeeDocuments
from app6_master.models import Designation
from django.contrib import messages

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from helpers.decorators import super_admin_only, login_required, employee_edit_permission
from helpers.pagination import paginate
import os
import json
from django.db.models import Q
app="app3_employee_management/" 
# Create your views here.


@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')
class EmployeeAdd(View):
    form=EmployeeCreationForm
    model=Employee
    html=app+"employee_list.html"
    def get(self,request,*args,**kwargs):
        data_list=self.model.objects.filter(is_active=True).order_by('-id')
        employee_list=paginate(request,data_list, 50)
        context={'form':self.form,'employee_list':employee_list}
        return render(request,self.html,context)   

    def post(self,request,*args,**kwargs):
        form_data=self.form(request.POST,request.FILES)
        aadhaar_number=request.POST.get('addhar_number')
        if (self.model.objects.filter(addhar_number=aadhaar_number).exists())==True:
            messages.error(request,'Aadhaar number is already present in database')
            return redirect('app3_employee_management:add_employee') 

        if form_data.is_valid():
            data=form_data.save()

            # if request.POST.get('designation'):
            #     designation=Designation.objects.get(id=request.POST.get('designation'))
            #     data.designation=designation
            #     data.save()
            messages.success(request, "Employee Added successfully")
        else:
            messages.error(request,str(form_data.errors))

        return redirect('app3_employee_management:add_employee')                 


@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')
class EmployeeEdit(View):
    form=EmployeeCreationForm
    model=Employee
    html=app+"edit_employee.html"
    def get(self,request,*args,**kwargs):
        u_id=kwargs.get('u_id')
        obj=self.model.objects.get(id=u_id)
        designation_list=Designation.objects.all()
        context={'form':self.form(instance=obj),'designation_list':designation_list,'obj':obj}
        return render(request,self.html,context)   

    def post(self,request,*args,**kwargs):
        u_id=kwargs.get('u_id')
        obj=self.model.objects.get(id=u_id)
        form_data=self.form(request.POST,request.FILES,instance=obj)

        if form_data.is_valid():
            data=form_data.save()
            
            # if request.POST.get('designation'):
            #     designation=Designation.objects.get(id=request.POST.get('designation'))
            #     data.designation=designation
            #     data.save()

            messages.success(request, "Employee Editted successfully")
        else:
            messages.error(request,str(form_data.errors))

        return redirect('app3_employee_management:edit_employee',(u_id))  

@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')
class EmployeeDelete(View):
    form=EmployeeCreationForm
    model=Employee
    def get(self,request,*args,**kwargs):
        u_id=kwargs.get('u_id')
        obj=self.model.objects.get(id=u_id)

        if obj.profile_pic:
            if len(obj.profile_pic) > 0:
                os.remove(obj.profile_pic.path)
        obj.delete()
        messages.success(request,"Employee is deleted.")
        return redirect('app3_employee_management:add_employee') 

@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')
class EmployeeDocumentsAdd(View):
    form=EmployeeDocumentForm
    model=EmployeeDocuments
    template=app+'documents.html'

    def get(self,request,*args,**kwargs):
        u_id=kwargs.get('u_id')
        employee=Employee.objects.get(id=u_id)
        all_docs=self.model.objects.filter(employee=employee)
        context={'doc_list':all_docs,'form':self.form,'u_id':u_id}
        return render(request,self.template,context)

    def post(self,request,*args,**kwargs):
        u_id=kwargs.get('u_id')
        employee=Employee.objects.get(id=u_id)

        form_data=self.form(request.POST,request.FILES)
        if form_data.is_valid():
            data=form_data.save()
            data.employee=employee
            data.save()
            messages.success(request,'Document is Added Succesfully')
        else:
            messages.error(request,str(form.errors))
        return redirect('app3_employee_management:employee_documents',u_id)
 

@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')
class EmployeeDocumentsDelete(View):
    model=EmployeeDocuments
    def get(self,request,*args,**kwargs):
        d_id=kwargs.get('d_id')
        obj=EmployeeDocuments.objects.get(id=str(d_id))
        u_id=obj.employee.id
        if obj.file_data:
            if len(obj.file_data) > 0:
                os.remove(obj.file_data.path)
        obj.delete()
        messages.success(request,"Document is deleted.")
        return redirect('app3_employee_management:employee_documents',u_id) 


@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')

class EmployeeSearchView(View):
    form=EmployeeCreationForm
    model=Employee
    template=app+"employee_list.html"
    def post(self,request,*args,**kwargs):
        query=request.POST.get('query')
        e_id=request.POST.get('e_id')
        employee_list=[]
        employee_list1=[]
        employee_list2=[]
        if e_id:
            employee_list=self.model.objects.filter(id=e_id)
        else:
            employee_list=self.model.objects.filter(Q(name__icontains=query) | Q(contact1__iexact=query) | Q(contact2__iexact=query))
        
        context={'form':self.form,'employee_list':employee_list,}   
        return render(request, self.template, context)
    
    def get(self,request,*args,**kwargs):
        return redirect('app3_employee_management:add_employee')

@method_decorator(login_required,name='dispatch')
@method_decorator(employee_edit_permission,name='dispatch')

class EmployeeFilterView(View):
    form=EmployeeCreationForm
    model=Employee
    template=app+"employee_list.html"
    def get(self,request,*args,**kwargs):
        filter_name=kwargs.get('filter_name')
        employee_list=[]
        if filter_name=='active':
            employee_list=self.model.objects.filter(is_active=True)
        elif filter_name=='inactive':
            employee_list=self.model.objects.filter(is_active=False)
        else:
            messages.error(request, "Use a Vaild Filter")
        employee_list=paginate(request,employee_list, 50)
        context={'form':self.form,'employee_list':employee_list,}   
        return render(request, self.template, context)

templates/app3_employee_management/documents.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Add Employee</h1>
        
      </div>
      <div>
        
      </div>
      
    </div>
  </div>
  <div class="card border-0 shadow">
    <div class="">
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow components-section">
          <div class="card-body">
            <div class="row mb-4">
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
              <div class="col-lg-4 col-sm-6" style='text-align:center;'>
                
              <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                  <tr>
                    <th class="border-0">Name</th>
                    <th class="border-0">Image</th>
                    <th class="border-0">Action</th>
                    
                  </tr>
                </thead>
                <tbody>
                  {% for doc in doc_list %}
                    <tr>
                      <td class="border-0 fw-bold">{{doc.name}}</td>
                      <td class="border-0 fw-bold">
                        {% if doc.file_data %}
                          <a target="_blank" href="{{doc.file_data.url}}">Click TO See</a>
                        {% endif %}
                      </td>
                      <td class="border-0 fw-bold">
                        <a href="{% url 'app3_employee_management:employee_document_delete' doc.id %}"><i class="bi bi-trash" title="Document Delete" style="font-size: 13px;color: orangered;"></i></a>
                        
                      </td>
                    </tr>
                    
                  {% endfor %}
                  
                </tbody>
              </table>

              <hr>
                {% include 'snippets/alert.html' %}
                <form method="POST" action="" enctype="multipart/form-data">
                  
                  <br>
                  {% csrf_token %}
                  {{form.as_p}}
                  <button typr="submit" class="btn btn-primary">Update Employee</button>
                </form>
              </div>
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
    </div>
  </div>  
{% endblock content %}

templates/app3_employee_management/edit_employee.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Add Employee</h1>
        
      </div>
      <div>
        
      </div>
      
    </div>
  </div>
  <div class="card border-0 shadow">
    <div class="">
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow components-section">
          <div class="card-body">
            <div class="row mb-4">
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
              <div class="col-lg-4 col-sm-6" style='text-align:center;'>
                {% include 'snippets/alert.html' %}
                <form method="POST" action="" enctype="multipart/form-data">
                  
                  <br>
                  {% csrf_token %}
                  {{form.as_p}}
                  <!-- <p>
                      <label for="id_designation">Designation:</label>
                      <select name="designation" class="form-control" type="text" required="required" id="id_designation">
                        {% if obj.designation %}
                          <option selected value="{{obj.designation.id}}">{{obj.designation}}</option>
                        {% endif %} 
                        {% for designation in designation_list %}
                              <option value="{{designation.id}}">{{designation.name}}</option>
                          {% endfor %}
                      </select>                   
                    </p> -->
                  <button typr="submit" class="btn btn-primary">Update Employee</button>
                </form>
              </div>
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
    </div>
  </div>  
{% endblock content %}

templates/app3_employee_management/employee_list.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">All Active Employee List</h1>
        
      </div>
      <div>
        <a data-bs-toggle="modal" data-bs-target="#employee_filter"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-funnel" style="color:red;"></i> Filter
        </a>
        <a data-bs-toggle="modal" data-bs-target="#search_employee"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-search" style="color:red;"></i> Search
        </a>
        <a data-bs-toggle="modal" data-bs-target="#modal-form-signup"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-plus-circle-dotted" style="color:red;"></i>  Add Employee
        </a>
      </div>
      
    </div>
  </div>
  {% include 'snippets/alert.html'%}
  <div class="card border-0 shadow">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
            <tr>
              <th class="border-0 rounded-start">ID</th>
              <th class="border-0">Name</th>
              <th class="border-0">Contact</th>
              <th class="border-0">Designation</th>
              <th class="border-0">Status</th>
              <th class="border-0">Settings</th>
              
            </tr>
          </thead>
          <tbody>
            {% for e in employee_list %}
              <tr>
                <td class="border-0 fw-bold">{{e.id}}</td>
                <td class="border-0 fw-bold">{{e.name}}</td>
                <td class="border-0 fw-bold">{{e.contact1}}</td>
                <td class="border-0 fw-bold">{{e.designation}}</td>
                <td class="border-0 fw-bold">
                  {% if e.is_active == True %}
                    <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#active_inactive{{user.id}}">Active</button>
                  {% else %}
                    <button class="btn btn-danger" type="button" data-bs-toggle="modal" data-bs-target="#active_inactive{{user.id}}">Inactive</button>
                  {% endif %}
                </td>
                <td class="border-0 fw-bold">
                  <a href="{% url 'app3_employee_management:edit_employee' e.id %}"><i class="bi bi-gear" title="Edit Employee" style="font-size: 22px;color: #03035a;"></i></a>
                  <i class="bi bi-trash" title="Employee Delete" style="font-size: 25px;color: orangered;" data-bs-toggle="modal" data-bs-target="#employee_delete{{user.id}}"></i>
                  <a href="{% url 'app3_employee_management:employee_documents' e.id %}"><i title="Documents" class="bi bi-file-zip" style="font-size: 23px;color: #b816cc;"></i></a>
                </td>
              </tr>
              {% include 'app3_employee_management/multi_modal.html'%}
            {% endfor %}
            
          </tbody>
        </table>
        <div class="pagination" style="float: right;">
            <span class="step-links">
                {% if employee_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ employee_list.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ employee_list.number }} of {{ employee_list.paginator.num_pages }}.
                </span>

                {% if employee_list.has_next %}
                    <a href="?page={{ employee_list.next_page_number }}">next</a>
                    <a href="?page={{ employee_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
  </div>  
  {% include 'app3_employee_management/modal.html'%}

{% endblock content %}

templates/app3_employee_management/modal.html
<div class="modal fade" id="modal-form-signup" tabindex="-1" role="dialog"
    aria-labelledby="modal-form-signup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
        <div class="modal-body p-0">
        <div class="card p-3 p-lg-4"><button type="button" class="btn-close ms-auto"
            data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h4">Add Employee</h1>
            </div>
            <form action="{% url 'app3_employee_management:add_employee' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                <div>
                    {{form.as_p}}
                    <!-- <p>
                        <label for="id_designation">Designation:</label>
                        <select name="designation" class="form-control" type="text" required="required" id="id_designation">
                            {% for designation in designation_list %}
                                <option value="{{designation.id}}">{{designation.name}}</option>
                            {% endfor %}
                        </select>                   
                    </p> -->
                </div>
               
            <div class="d-grid">
                <button type="submit" class="btn btn-gray-800">Add Employee</button>
            </div>
            </form>
        
        </div>
        </div>
    </div>
    </div>
</div>

<!--search employee-->
<div class="modal fade" id="search_employee" tabindex="-1" role="dialog" aria-labelledby="modal-form-signup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="card p-3 p-lg-4"><button type="button" class="btn-close ms-auto"
                    data-bs-dismiss="modal" aria-label="Close"></button>
                    <div class="text-center text-md-center mb-4 mt-md-0">
                    <h1 class="mb-0 h4">Search Employee</h1>
                    <small class="mb-0" style="color: red;">Using Id, Contact, Name</small>
                    </div>
                    <form action="{% url 'app3_employee_management:employee_search' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media}}
                        <div>
                            <input type="text" name="e_id" class="form-control" placeholder="Search By Id"/>
                            <center>OR</center>
                            <input type="text" name="query" class="form-control" placeholder="Search by Contact or name"/>
                        </div>
                        <br>
                    
                    <div class="d-grid">
                        <button type="submit" class="btn btn-gray-800">Search</button>
                    </div>
                    </form>
                
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Employee Filter-->
<div class="modal fade" id="employee_filter" tabindex="-1" role="dialog" aria-labelledby="modal-achievement" aria-hidden="true">
    <div class="modal-dialog modal-tertiary modal-dialog-centered" role="document">
        <div class="modal-content"><button type="button" class="btn-close theme-settings-close fs-6 ms-auto"
                data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-header mx-auto">
                <p class="lead mb-0 text-white">Select Employee Status</p>
            </div>
            <div class="modal-body pt-0">
            </div>
            <div class="modal-footer d-flex justify-content-center pt-0 pb-3">
                <a href="{% url 'app3_employee_management:employee_filter' 'active'%}"><button type="button"  class="btn btn-sm btn-success text-tertiary">Active</button></a>
                <a href="{% url 'app3_employee_management:employee_filter' 'inactive'%}"><button type="button"  class="btn btn-sm btn-danger text-tertiary">Inactive</button></a>
            </div>
        </div>
    </div>
</div>

templates/app3_employee_management/multi_modal.html
<!-- Delete Employee-->
<div class="modal fade" id="employee_delete{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="modal-achievement" aria-hidden="true">
    <div class="modal-dialog modal-tertiary modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="btn-close theme-settings-close fs-6 ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-header mx-auto">
                <p class="lead mb-0 text-white">Confirm for Delete</p>
            </div>
            <div class="modal-body pt-0">
            </div>
            <div class="modal-footer d-flex justify-content-center pt-0 pb-3">
                <a href="{% url 'app3_employee_management:employee_delete' e.id %}"><button type="button"  class="btn btn-sm btn-success text-tertiary">Delete</button></a>
                <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn btn-sm btn-danger text-tertiary">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!---->