app4_product/urls.py
from django.urls import path
from .views import ProductCreationView, ProductUpdateView, ProductdelteView, ProductsearchView
app_name = 'app4_product'
urlpatterns = [
   path('product/product_list_create', ProductCreationView.as_view(), name="product_list_create"),
   path('product/product_update/<str:p_id>', ProductUpdateView.as_view(), name="product_update"),
   path('product/product_delete/<str:p_id>', ProductdelteView.as_view(), name="product_delete"),
   path('product/search_product',ProductsearchView.as_view(),name="search_product"),
] 

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1_authentication.urls')),
    path('auth/',include('app1_authentication.urls')),
    path('user_manage/',include('app1_authentication.urls')),
    path('admin_dashboard/',include('app2_admin_dashboard.urls')),
    path('employee_manage/',include('app3_employee_management.urls')),
    path('product_manage/',include('app4_product.urls')),
    path('raw_materials/',include('app5_raw_materials.urls')),
    path('master_data/',include('app6_master.urls')),
    path('rms/',include('app7_rms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app4_product/models.py
from django.db import models
from app6_master.models import Unit, ItemCode
from django.contrib import admin
# Create your models here.

class Product(models.Model):
    name=models.CharField(max_length=255,null=True,blank=True)

    unit=models.ForeignKey(Unit, on_delete=models.SET_NULL, blank=True, null=True)
    Item_code=models.ForeignKey(ItemCode, on_delete=models.SET_NULL, blank=True, null=True)

    remarks=models.TextField(null=True,blank=True)
    def __str__(self):
        return (str(self.id) +'-'+ self.name)
admin.site.register(Product)

app4_product/forms.py
from django import forms
from .models import Product
from app6_master.models import Unit, ItemCode

class ProductCreationForm(forms.ModelForm):
    class Meta:
        model=Product
        fields='__all__'

    name=forms.CharField(required=True)
    # Item_code=forms.ChoiceField(choices=[(i.pk, i) for i in ItemCode.objects.all()])
    # unit=forms.ChoiceField(choices=[(u.pk, u) for u in Unit.objects.all()])
    Item_code=forms.ModelChoiceField(queryset=ItemCode.objects.all())
    unit=forms.ModelChoiceField(queryset=Unit.objects.all())
    remarks=forms.CharField(required=True)

    name.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Name',"required":"required"})
    Item_code.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Remarks',"required":"required"})
    unit.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Remarks',"required":"required"})
    remarks.widget.attrs.update({'class': 'form-control','type':'text','placeholder':'Enter Remarks',"required":"required"})
   
    # def clean(self):
    #     if self.cleaned_data['sku_start']:
    #         if (Product.objects.filter(sku_start=self.cleaned_data['sku_start'])).exists()==True:
    #             raise forms.ValidationError("Same SKU code is already present")
    #     else:
    #         raise forms.ValidationError("SKU code is needed")

    

app4_product/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View

from .forms import ProductCreationForm
from .models import Product
from app6_master.models import ItemCode, Unit

from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from helpers.decorators import super_admin_only, login_required, product_edit_permission
from helpers.pagination import paginate
import os


app="app4_product/" 
# Create your views here.


@method_decorator(login_required,name='dispatch')
@method_decorator(product_edit_permission,name='dispatch')
# Create your views here.
class ProductCreationView(View):
    model=Product
    form=ProductCreationForm
    template=app+"product_list.html"
    
    def get(self,request,*args,**kwargs):
        product_list=self.model.objects.all().order_by('-id')
        product_list=paginate(request, product_list, 10)
        context={'product_list':product_list,'form':self.form}
        return render(request,self.template,context)

    def post(self,request,*args,**kwargs):
        form_data=self.form(request.POST)
        if form_data.is_valid():
            data=form_data.save()
            message=data.name +' with code ' +'is crated'
            messages.success(request,message)
        else:
            messages.error(request,str(form_data.errors))
            
        return redirect ('app4_product:product_list_create')


@method_decorator(login_required,name='dispatch')
@method_decorator(product_edit_permission,name='dispatch')
class ProductUpdateView(View):
    model=Product
    form=ProductCreationForm
    template=app+"edit_product.html"
    def get(self,request,*args,**kwargs):
        id=kwargs.get('p_id')
        product=self.model.objects.get(id=id)
        form=self.form(instance=product)
        context={'form':form}
        return render(request,self.template,context)
    
    def post(self,request,*args,**kwargs):
        id=kwargs.get('p_id')
        product=self.model.objects.get(id=id)
        ser = self.form(request.POST,request.FILES,instance=product)
        if ser.is_valid():
            ser.save()
            messages.success(request, "Product is updated")
            return redirect('app4_product:product_list_create')
        else:
            messages.error(request, str(ser.errors))
            return redirect('app4_product:product_list_create')


@method_decorator(login_required,name='dispatch')
@method_decorator(product_edit_permission,name='dispatch')
class ProductdelteView(View):
    model=Product
    template=app+"edit_product.html"
    def get(self,request,*args,**kwargs):
        id=kwargs.get('p_id')
        product=self.model.objects.get(id=id)
        product.delete()
        messages.success(request, "Product is deleted.")
        return redirect('app4_product:product_list_create')

@method_decorator(login_required,name='dispatch')
@method_decorator(product_edit_permission,name='dispatch')

class ProductsearchView(View):
    model=Product
    form=ProductCreationForm
    template=app+"product_list.html"
    def post(self,request,*args,**kwargs):
        query=request.POST.get('query')
        product=[]
        try:
            id=int(query)
            product=self.model.objects.filter(id=id).first()

        except:
            product=self.model.objects.filter(name__icontains=query)

        if product != []:
            context={'product_list':product,'form':self.form}

        else:
            context={'product_list':product,'form':self.form}
            messages.error(request,"Product Not Found.")

        return render(request, self.template, context)

        
    #     eid = int(eid)
    #     emp2 = Employee.objects.filter(id=eid)
    #     context = {"product_list": emp2}
    #     return render(request, "emp_template/emp_list.html", context)
    # except ValueError:
    #     pass
    # emp3 = Employee.objects.filter(Aadhaar_NO__icontains=eid)
    # emp = emp1 | emp3
    # context = {"product_list": emp}

templates/app4_product/edit_product.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Update Product</h1>
        
      </div>
      <div>
        
      </div>
      
    </div>
  </div>
  <div class="card border-0 shadow">
    <div class="">
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow components-section">
          <div class="card-body">
            <div class="row mb-4">
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
              <div class="col-lg-4 col-sm-6" style='text-align:center;'>
                {% include 'snippets/alert.html' %}
                <form method="POST" action="" enctype="multipart/form-data">
                  
                  <br>
                  {% csrf_token %}
                  {{form.as_p}}
                  <button typr="submit" class="btn btn-primary">Update</button>
                </form>
              </div>
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
    </div>
  </div>  
{% endblock content %}

templates/app4_product/modal.html
<div class="modal fade" id="product_creation" tabindex="-1" role="dialog"
    aria-labelledby="modal-form-signup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
        <div class="modal-body p-0">
        <div class="card p-3 p-lg-4"><button type="button" class="btn-close ms-auto"
            data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h4">Add Product</h1>
            </div>
            <form action="{% url 'app4_product:product_list_create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                <div>
                    {{form.as_p}}
                </div>
               
            <div class="d-grid">
                <button type="submit" class="btn btn-gray-800">Add Product</button>
            </div>
            </form>
        
        </div>
        </div>
    </div>
    </div>
</div>

templates/app4_product/multi_modal.html
<!-- Delete Product-->
<div class="modal fade" id="product_delete{{product.id}}" tabindex="-1" role="dialog" aria-labelledby="modal-achievement" aria-hidden="true">
    <div class="modal-dialog modal-tertiary modal-dialog-centered" role="document">
        <div class="modal-content">
            <button type="button" class="btn-close theme-settings-close fs-6 ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-header mx-auto">
                <p class="lead mb-0 text-white">Confirm for Delete</p>
            </div>
            <div class="modal-body pt-0">
            </div>
            <div class="modal-footer d-flex justify-content-center pt-0 pb-3">
                <a href="{% url 'app4_product:product_delete' product.id %}"><button type="button"  class="btn btn-sm btn-success text-tertiary">Delete</button></a>
                <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn btn-sm btn-danger text-tertiary">Cancel</button>
            </div>
        </div>
    </div>
</div>

templates/app4_product/product_list.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">All Prouct List</h1>
        
      </div>
      <div>
        <a data-bs-toggle="modal" data-bs-target="#search_product"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-search" style="color:red;"></i>  Search Product
        </a>
        <a data-bs-toggle="modal" data-bs-target="#product_creation"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-plus-circle-dotted" style="color:red;"></i>  Add Product
        </a>
      </div>
      
    </div>
  </div>
  {% include 'snippets/alert.html'%}
  <div class="card border-0 shadow">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
            <tr>
              <!--th class="border-0 rounded-start">id</th-->
              <th class="border-0 rounded-start" style="text-transform: none;font-size: 18px;">Item Code</th>
              <th class="border-0" style="text-transform: none;font-size: 18px;">Item</th>
              <th class="border-0" style="text-transform: none;font-size: 18px;">Item Code</th>
              <th class="border-0" style="text-transform: none;font-size: 18px;">Unit</th>
              <th class="border-0" style="text-transform: none;font-size: 18px;">Remarks</th>
              <th class="border-0" style="text-transform: none;font-size: 18px;">Settings</th>
            </tr>
          </thead>
          <tbody>
            {% for product in product_list %}
              <tr>
                <!--td class="border-0 fw-bold">{{product.id}}</td-->
                <td class="border-0 fw-bold">{{product.sku_start}}{{product.id}}</td>
                <td class="border-0 fw-bold">{{product.name}}</td>
                <td class="border-0 fw-bold">{{product.unit}}</td>
                <td class="border-0 fw-bold">{{product.Item_code}}</td>
                <td class="border-0 fw-bold">{{product.remarks}}</td>
                
                <td class="border-0 fw-bold">
                  <a href="{% url 'app4_product:product_update' product.id %}"><i class="bi bi-pencil-square" title="Edit Product" style="font-size: 22px;color: #fb9d38;"></i></a>
                  <a ><i data-bs-toggle="modal" data-bs-target="#product_delete{{product.id}}" class="bi bi-trash" title="Delet Product" style="font-size: 22px;color: #ec1f0d;"></i></a>
                  <a ><i class="bi bi-gear" title="Edit Employee" style="font-size: 22px;color: #03035a;"></i></a>
                  <a ><i title="Documents" class="bi bi-file-zip" style="font-size: 23px;color: #b816cc;"></i></a>
                </td>
              </tr>
              {% include 'app4_product/multi_modal.html'%}
            {% endfor %}
            
          </tbody>
        </table>
        <div class="pagination" style="float: right;">
            <span class="step-links">
                {% if product_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ product_list.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ product_list.number }} of {{ product_list.paginator.num_pages }}.
                </span>

                {% if product_list.has_next %}
                    <a href="?page={{ product_list.next_page_number }}">next</a>
                    <a href="?page={{ product_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
  </div>  
  {% include 'app4_product/modal.html'%}

{% endblock content %}