app1_authentication/urls.py
from django.urls import path
from .views import Login, LogOut, UserList, UserCreation, UserStateChange, Update_user, UserPermissionAdd, UserPasswordChange
app_name = 'app1_authentication'
urlpatterns = [
    path('login',Login.as_view(),name="login"),
    path('logout',LogOut.as_view(),name="logout"),

    path('user_manage/user_list',UserList.as_view(),name="user_list"),
    path('user_manage/create_user',UserCreation.as_view(),name="create_user"),
    path('user_manager/user_state_chage/<str:u_id>/<str:state>/',UserStateChange.as_view(),name="user_state_chage"),
    path('user_manager/update_user',Update_user.as_view(),name="update_user"),
    path('user_manager/password_change/<str:u_id>',UserPasswordChange.as_view(),name="password_change"),
    path('user_manager/user_permission_add/<str:u_id>',UserPermissionAdd.as_view(),name="user_permission_add"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1_authentication.urls')),
    path('auth/',include('app1_authentication.urls')),
    path('user_manage/',include('app1_authentication.urls')),
    path('admin_dashboard/',include('app2_admin_dashboard.urls')),
    path('employee_manage/',include('app3_employee_management.urls')),
    path('product_manage/',include('app4_product.urls')),
    path('raw_materials/',include('app5_raw_materials.urls')),
    path('master_data/',include('app6_master.urls')),
    path('rms/',include('app7_rms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1_authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib import admin

class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


class User(AbstractBaseUser, PermissionsMixin):
	# user field
	username = models.CharField(max_length=100, unique=True, null=True,blank=True)
	password = models.TextField(null=True,blank=True)
	email = models.EmailField(null=True,blank=True)
	first_name = models.CharField(max_length=100, null=True)
	last_name = models.CharField(max_length=100, null=True)
	
	is_staff = models.BooleanField(default=False)
	created_on = models.DateField(auto_now_add=True)
	is_active = models.BooleanField(default=True)

	contact_number = models.CharField(max_length=10, null=True)
	USERNAME_FIELD = "username"	
	REQUIRED_FIELDS = ["email","password"]

	objects = MyAccountManager()

	def save(self, *args, **kwargs):
		super(User, self).save(*args, **kwargs)

	def create_new_token():
		pass
		
	def get_full_name(self):
		full_name = None
		if self.first_name or self.last_name:
			full_name = self.first_name + " " + self.last_name
		return full_name if full_name else self.email

	@property
	def full_name(self):
		return self.get_full_name()

admin.site.register(User)

class PerissionAssign(models.Model):
	Access=(
		('accounts','accounts'),
		('product','product'),
		('employee_manage','employee_manage')
	)
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	name=models.CharField(max_length=255,choices=Access,null=True,blank=True)

app1_authentication/forms.py
from django import forms
from .models import User, PerissionAssign

class UserCreationForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password','password2','first_name','last_name','contact_number','is_active',]

    username=forms.CharField(required = True)
    password=forms.CharField(required = True)
    password2=forms.CharField(required = True)
    first_name=forms.CharField(required = True)
    last_name=forms.CharField(required = True)
    is_active=forms.RadioSelect()
    is_staff=forms.RadioSelect()
    contact_number=forms.IntegerField()
    username.widget.attrs.update({'class': 'form-control','placeholder':'Enter UserName',"required":"required"})
    password.widget.attrs.update({'class': 'form-control','type':'password','placeholder':'Enter Password',"required":"required"})
    password2.widget.attrs.update({'class': 'form-control','type':'password','placeholder':'Confirm Password',"required":"required"})
    first_name.widget.attrs.update({'class': 'form-control','placeholder':'Enter first_name',"required":"required"})
    last_name.widget.attrs.update({'class': 'form-control','placeholder':'Enter last_name',"required":"required"})
    contact_number.widget.attrs.update({'type':'number','class': 'form-control','placeholder':'Enter Contact',"required":"required"})

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2'] :
            raise forms.ValidationError("PAssword is no same")
        # username=self.cleaned_data['username']
        # if not username:    
        #     raise forms.ValidationError("UserName Field CanNot Be Empty")

        # password=self.cleaned_data['password']
        # if not password:
        #     raise forms.ValidationError("Password Field CanNot Be Empty")

        # password=self.cleaned_data['password']
        # if not password:
        #     raise forms.ValidationError("Password Field CanNot Be Empty")

class LoginForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password']
    username=forms.CharField()
    password=forms.CharField()

    username.widget.attrs.update({'autofocus':'autofocus' ,'class': 'form-control','placeholder':'Enter UserName',"required":"required"})
    password.widget.attrs.update({'class': 'form-control','type':'password','placeholder':'Enter Password',"required":"required"})
    def clean(self):

        username=self.cleaned_data['username']
        if not username:    
            raise forms.ValidationError("UserName Field CanNot Be Empty")

        password=self.cleaned_data['password']
        if not password:
            raise forms.ValidationError("Password Field CanNot Be Empty")

app1_authentication/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views import View
from django.template.loader import render_to_string
from .forms import LoginForm, UserCreationForm
from .models import User, PerissionAssign
from django.contrib import messages
from django.contrib.auth.models import Permission

from django.contrib.auth.models import auth
from django.contrib.auth.hashers import check_password, make_password
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from helpers.decorators import super_admin_only
app="app1_authentication/"

class Login(View):
    form=LoginForm
    model=User
    template=app+"login.html"
    #template="master/master.html"
    def get(self,request):
        context={"form":self.form}
        return render(request,self.template,context)
    
    def post(self,request):
        data=request.POST
        form_data=self.form(data)
        if form_data.is_valid():  
            user=auth.authenticate(username=data['username'], password=data['password'])
        if user is not None:
            auth.login(request,user)
            messages.success(request, 'successfully Login.') 
            if user.is_staff==True:
                return redirect('/admin_dashboard/')
        else:
            messages.error(request, 'Login Failed') 
        return redirect('/login')


@method_decorator(login_required, name='dispatch')
class LogOut(View):
    def get(self,request):
        auth.logout(request)
        messages.success(request, 'successfully Logout.')
        return redirect('/login')


@method_decorator(super_admin_only, name='dispatch')
class UserList(View):
    html="app1_authentication/users/user_list.html"
    def get(self,request):
        all_users=User.objects.all()
        context={'user_list':all_users,}
        return render(request,self.html,context)

@method_decorator(super_admin_only, name='dispatch')
class UserCreation(View):
    form=UserCreationForm
    html="app1_authentication/users/create_user.html"
    def get(self,request):
        context={'form':self.form}
        return render(request,self.html,context)
    
    def post(self,request):
        form_data=self.form(request.POST)
        if form_data.is_valid():
            
            f_data=form_data.save(commit=False)
            f_data.password=make_password(request.POST.get('password'))
            f_data.save()

            messages.success(request, "Data is saved with no errors.")
        else:

            messages.error(request,str  (form_data.errors))
        context={'form':self.form}
        return render(request,self.html,context)

@method_decorator(super_admin_only, name='dispatch')
class UserPasswordChange(View):
    def post(self,request,*args,**kwargs):
        obj=User.objects.get(id=kwargs.get("u_id"))
        password=request.POST.get('password')
        obj.password=make_password(password)
        obj.save()
        messages.success(request,"Password is Changed succesfully.")
        return redirect('app1_authentication:user_list')

@method_decorator(super_admin_only, name='dispatch')
class UserStateChange(View):
    def get(self,request,*args,**kwargs):
        obj=User.objects.get(id=kwargs.get("u_id"))
        if kwargs.get("state")=="active":
            obj.is_active=True
        else:
            obj.is_active=False
        obj.save()
        messages.success(request,"Users state is changed now.")
        return redirect('app1_authentication:user_list')

@method_decorator(super_admin_only, name='dispatch')
class UserPermissionAdd(View):
    model=PerissionAssign
    def post(self,request,*args,**kwargs):
        obj=User.objects.get(id=kwargs.get("u_id"))
        p_name=request.POST.get('permission')
        if (self.model.objects.filter(user=obj,name=p_name).exists())==True:
            messages.error(request,'Permission Is already present')
        else:
            self.model.objects.create(user=obj,name=p_name)
            messages.success(request,"Permission Is Added")
        return redirect('app1_authentication:user_list')

@method_decorator(super_admin_only, name='dispatch')
class Update_user(View):
    form=UserCreationForm
    html="app1_authentication/users/create_user.html"
    def get(self,request):
        context={'form':self.form}
        return render(request,self.html,context)
    def put(self,request):
        pass

templates/app1_authentication/users/create_user.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Add Employee</h1>
        
      </div>
      <div>
        
      </div>
      
    </div>
  </div>
  <div class="card border-0 shadow">
    <div class="">
    <div class="row">
      <div class="col-12 mb-4">
        <div class="card border-0 shadow components-section">
          <div class="card-body">
            <div class="row mb-4">
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
              <div class="col-lg-4 col-sm-6" style='text-align:center;'>
                {% include 'snippets/alert.html' %}
                <form method="POST" action="">
                  
                  <br>
                  {% csrf_token %}
                  {{form.as_p}}
                  <button typr="submit" class="btn btn-primary">Create User</button>
                </form>
              </div>
              <div class="col-lg-4 col-sm-6">
                <!--empty-->
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
    </div>
  </div>  
{% endblock content %}

templates/app1_authentication/users/modal.html
<!-- modal for active and inactive user-->
<div class="modal fade" id="active_inactive{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="modal-achievement" aria-hidden="true">
    <div class="modal-dialog modal-tertiary modal-dialog-centered" role="document">
        <div class="modal-content"><button type="button" class="btn-close theme-settings-close fs-6 ms-auto"
                data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-header mx-auto">
                <p class="lead mb-0 text-white">Select Option</p>
            </div>
            <div class="modal-body pt-0">
            </div>
            <div class="modal-footer d-flex justify-content-center pt-0 pb-3">
                <a href="{% url 'app1_authentication:user_state_chage' user.id 'active'%}"><button type="button"  class="btn btn-sm btn-success text-tertiary">Active</button></a>
                <a href="{% url 'app1_authentication:user_state_chage' user.id 'inactive'%}"><<button type="button"  class="btn btn-sm btn-danger text-tertiary">Inactive</button></a>
            </div>
        </div>
    </div>
</div>

<!-- modal for permission add-->
<div class="modal fade" id="permission{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="modal-form"
aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-body p-0">
        <div class="card p-3 p-lg-4"><button type="button" class="btn-close ms-auto"
            data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h4">Manage permission</h1>
            <small>ctl+click to select more than one</small>
        </div>
        <form action="{% url "app1_authentication:user_permission_add" user.id %}" method="POST" class="mt-4">
            {% csrf_token %}
            <select class="form-select" name="permission" aria-label="Default select example">
            <option selected>Access</option>
            <option value="accounts">accounts</option>
            <option value="product">product</option>
            </select>
            <br>
            <div class="d-grid">
            <button type="submit" class="btn btn-gray-800">Add</button>
            </div>
        </form>
        
        </div>
    </div>
    </div>
</div>
</div>

<!-- modal for password change-->
<div class="modal fade" id="password_change{{user.id}}" tabindex="-1" role="dialog" aria-labelledby="modal-form"
aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-body p-0">
        <div class="card p-3 p-lg-4"><button type="button" class="btn-close ms-auto"
            data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h4">Change Password</h1>
            <small>Enter a Strong Password</small>
        </div>
        <form action="{% url "app1_authentication:password_change" user.id %}" method="POST" class="mt-4">
            {% csrf_token %}
            <input class="form-control" name="password" placeholder="Enter Password" type="text" required/>
            <br>
            <div class="d-grid">
            <button type="submit" class="btn btn-gray-800">Update</button>
            </div>
        </form>
        
        </div>
    </div>
    </div>
</div>
</div>

templates/app1_authentication/users/user_list.html
{% extends 'master/master.html' %}
{% load static %}
{% block content %}
  <div class="py-4">

    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">All User List</h1>
        
      </div>
      <div>
        

        <a href="{% url "app1_authentication:create_user" %}"
          class="btn btn-outline-gray-600 d-inline-flex align-items-center">
          <i class="bi bi-plus-circle-dotted" style="color:red;"></i>  Add User
        </a>
      </div>
      
    </div>
  </div>
  {% include 'snippets/alert.html'%}
  <div class="card border-0 shadow">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
            <tr>
              <th class="border-0 rounded-start">ID</th>
              <th class="border-0">Name</th>
              <th class="border-0">User-Name</th>
              <th class="border-0">Contact</th>
              <th class="border-0">Status</th>
              <th class="border-0">Settings</th>
              
            </tr>
          </thead>
          <tbody>
            {% for user in user_list %}
              <tr>
                <td class="border-0 fw-bold">{{user.id}}</td>
                <td class="border-0 fw-bold">{{user.first_name}} {{user.last_name}}</td>
                <td class="border-0 fw-bold">{{user.username}}</td>
                <td class="border-0 fw-bold">{{user.contact_number}}</td>
                <td class="border-0 fw-bold">
                  {% if user.is_active == True %}
                    <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#active_inactive{{user.id}}">Active</button>
                  {% else %}
                    <button class="btn btn-danger" type="button" data-bs-toggle="modal" data-bs-target="#active_inactive{{user.id}}">Inactive</button>
                  {% endif %}
                </td>
                <td class="border-0 fw-bold">
                  <i class="bi bi-gear" title="settings" style="font-size: 22px;color: orangered;" data-bs-toggle="modal" data-bs-target="#permission{{user.id}}"></i>
                  <i class="bi bi-key" title="Password Change" style="font-size: 25px;color: orangered;" data-bs-toggle="modal" data-bs-target="#password_change{{user.id}}"></i>
                </td>
              </tr>
              {% include 'app1_authentication/users/modal.html'%}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>  
{% endblock content %}