app1_authentication/urls.py
from django.urls import path
from .views import Login, LogOut, UserList, UserCreation, UserStateChange, Update_user, UserPermissionAdd, UserPasswordChange
app_name = 'app1_authentication'
urlpatterns = [
    path('login',Login.as_view(),name="login"),
    path('logout',LogOut.as_view(),name="logout"),

    path('user_manage/user_list',UserList.as_view(),name="user_list"),
    path('user_manage/create_user',UserCreation.as_view(),name="create_user"),
    path('user_manager/user_state_chage/<str:u_id>/<str:state>/',UserStateChange.as_view(),name="user_state_chage"),
    path('user_manager/update_user',Update_user.as_view(),name="update_user"),
    path('user_manager/password_change/<str:u_id>',UserPasswordChange.as_view(),name="password_change"),
    path('user_manager/user_permission_add/<str:u_id>',UserPermissionAdd.as_view(),name="user_permission_add"),
]

app4_product/urls.py
from django.urls import path
from .views import ProductCreationView, ProductUpdateView, ProductdelteView, ProductsearchView
app_name = 'app4_product'
urlpatterns = [
   path('product/product_list_create', ProductCreationView.as_view(), name="product_list_create"),
   path('product/product_update/<str:p_id>', ProductUpdateView.as_view(), name="product_update"),
   path('product/product_delete/<str:p_id>', ProductdelteView.as_view(), name="product_delete"),
   path('product/search_product',ProductsearchView.as_view(),name="search_product"),
] 

app6_master/urls.py
from django.urls import path
from .views import DesignationView, UnitView, ItemCodeView, ItemCodeEditView
app_name = 'app6_master'
urlpatterns = [
   path('master/designation',DesignationView.as_view(),name="designation"),
   path('master/unit',UnitView.as_view(),name="unit"),
   path('master/item_code',ItemCodeView.as_view(),name="item_code"),
   path('master/item_code_edit/<str:i_id>',ItemCodeEditView.as_view(),name="item_code_edit"),
] 

app7_rms/urls.py
from django.urls import path
from .views import RMSView, RMSOperationView, RMSFilterView
app_name = 'app7_rms'
urlpatterns = [
    path('admin_rms/rms_list_or_create',RMSView.as_view(),name="rms_list_or_create"),
    path('admin_rms/rms_operation/<str:m_id>/<str:operation>',RMSOperationView.as_view(),name="rms_operation"),
    path('admin_rms/rms_filter/<str:filter>',RMSFilterView.as_view(),name="rms_filter"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1_authentication.urls')),
    path('auth/',include('app1_authentication.urls')),
    path('user_manage/',include('app1_authentication.urls')),
    path('admin_dashboard/',include('app2_admin_dashboard.urls')),
    path('employee_manage/',include('app3_employee_management.urls')),
    path('product_manage/',include('app4_product.urls')),
    path('raw_materials/',include('app5_raw_materials.urls')),
    path('master_data/',include('app6_master.urls')),
    path('rms/',include('app7_rms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/master/head.html
{% load static %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>UniBon | ERP</title>
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="title" content="Volt - Premium Bootstrap 5 Dashboard">
  <meta name="author" content="Themesberg">
  <meta name="description"
    content="">
  <meta name="keywords", th
    content="">
  <link rel="canonical"
    href="">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://demo.themesberg.com/volt-pro">
  <meta property="og:title" content="Volt - Premium Bootstrap 5 Dashboard">
  <meta property="og:description"
    content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
  <meta property="og:image"
    content="/../../themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg'%}">
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://demo.themesberg.com/volt-pro">
  <meta property="twitter:title" content="Volt - Premium Bootstrap 5 Dashboard">
  <meta property="twitter:description"
    content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
  <meta property="twitter:image"
    content="/../../themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg'%}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'master/assets/img/favicon/apple-touch-icon.png'%}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'master/assets/img/favicon/favicon-32x32.png'%}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'master/assets/img/favicon/favicon-16x16.png'%}">
  <link rel="manifest" href="{% static 'master/assets/img/favicon/site.webmanifest'%}">
  <link rel="mask-icon" href="{% static 'master/assets/img/favicon/safari-pinned-tab.svg'%}" color="#ffffff">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#ffffff">
  <link type="text/css" href="{% static 'master/vendor/sweetalert2/dist/sweetalert2.min.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/notyf/notyf.min.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/fullcalendar/main.min.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/apexcharts/dist/apexcharts.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/dropzone/dist/min/dropzone.min.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/choices.js/public/assets/styles/choices.min.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/vendor/leaflet/dist/leaflet.css'%}" rel="stylesheet">
  <link type="text/css" href="{% static 'master/assets/volt.css'%}" rel="stylesheet">
</head>

templates/master/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

{% include 'master/head.html' %}

<body>
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-THQTXJ7" height="0" width="0"
      style="display:none;visibility:hidden"></iframe>
  </noscript>
  {% include "master/nav.html" %}
  <main class="content">
    <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
      <div class="container-fluid px-0">
        <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
          <div class="d-flex align-items-center"><button id="sidebar-toggle"
              class="sidebar-toggle me-3 btn btn-icon-only d-none d-lg-inline-block align-items-center justify-content-center"><svg
                class="toggle-icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                  clip-rule="evenodd"></path>
              </svg></button>
           
          </div>
          <ul class="navbar-nav align-items-center">
            <li class="nav-item dropdown"><a class="nav-link text-dark notification-bell unread dropdown-toggle"
                data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown"
                data-bs-display="static" aria-expanded="false"><svg class="icon icon-sm text-gray-900"
                  fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z">
                  </path>
                </svg></a>
              <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                <div class="list-group list-group-flush"><a href="#"
                    class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a> <a
                    href="../calendar.html" class="list-group-item list-group-item-action border-bottom">
                    <div class="row align-items-center">
                      <div class="col-auto"> <img alt="Image placeholder"
                          src="{% static 'master/assets/img/team/profile-picture-1.jpg'%}" class="avatar-md rounded"></div>
                      <div class="col ps-0 ms-2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                          </div>
                          <div class="text-end"><small class="text-danger">a few moments ago</small></div>
                        </div>
                        <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.
                        </p>
                      </div>
                    </div>
                  </a><a href="../tasks.html" class="list-group-item list-group-item-action border-bottom">
                    <div class="row align-items-center">
                      <div class="col-auto"> <img alt="Image placeholder"
                          src="{% static 'master/assets/img/team/profile-picture-2.jpg'%}" class="avatar-md rounded"></div>
                      <div class="col ps-0 ms-2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                          </div>
                          <div class="text-end"><small class="text-danger">2 hrs ago</small></div>
                        </div>
                        <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                      </div>
                    </div>
                  </a><a href="../tasks.html" class="list-group-item list-group-item-action border-bottom">
                    <div class="row align-items-center">
                      <div class="col-auto"> <img alt="Image placeholder"
                          src="{% static 'master/assets/img/team/profile-picture-3.jpg'%}" class="avatar-md rounded"></div>
                      <div class="col ps-0 m-2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                          </div>
                          <div class="text-end"><small>5 hrs ago</small></div>
                        </div>
                        <p class="font-small mt-1 mb-0">Tagged you in a document called "Financial plans",</p>
                      </div>
                    </div>
                  </a><a href="../single-message.html" class="list-group-item list-group-item-action border-bottom">
                    <div class="row align-items-center">
                      <div class="col-auto"> <img alt="Image placeholder"
                          src="{% static 'master/assets/img/team/profile-picture-4.jpg'%}" class="avatar-md rounded"></div>
                      <div class="col ps-0 ms-2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                          </div>
                          <div class="text-end"><small>1 d ago</small></div>
                        </div>
                        <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                      </div>
                    </div>
                  </a><a href="../single-message.html" class="list-group-item list-group-item-action border-bottom">
                    <div class="row align-items-center">
                      <div class="col-auto">
                         <img alt="Image placeholder" data-bs-toggle="modal" data-bs-target="#logout_modal" type="button" src="{% static 'master/assets/img/team/profile-picture-5.jpg'%}" class="avatar-md rounded"></div>
                      <div class="col ps-0 ms-2">
                        <div class="d-flex justify-content-between align-items-center">
                          <div>
                            <h4 class="h6 mb-0 text-small" data-bs-toggle="modal" data-bs-target="#logout_modal" type="button">Bonnie Green</h4>
                          </div>
                          <div class="text-end"><small>2 hrs ago</small></div>
                        </div>
                        <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing
                          page."</p>
                      </div>
                    </div>
                  </a><a href="#" class="dropdown-item text-center fw-bold rounded-bottom py-3"><svg
                      class="icon icon-xxs text-gray-400 me-1" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
                      <path fill-rule="evenodd"
                        d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
                        clip-rule="evenodd"></path>
                    </svg> View all</a></div>
              </div>
            </li>
            <li class="nav-item dropdown ms-lg-3"><a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                <div class="media d-flex align-items-center"><img class="avatar rounded-circle" alt="Image placeholder"
                    src="{% static 'master/assets/img/team/profile-picture-3.jpg'%}" data-bs-toggle="modal" data-bs-target="#logout_modal" type="button">
                  <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block"><span
                      class="mb-0 font-small fw-bold text-gray-900" data-bs-toggle="modal" data-bs-target="#logout_modal" type="button">Bonnie Green</span></div>
                </div>
              </a>
             
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    
    {% endblock content %}

  </main>
  {% include "master/modals.html" %}
</body>
{% include "master/scripts.html" %}

</html>

templates/master/modals.html
{% load static %}
<!--settings-->
<div class="modal fade" id="logout_modal" tabindex="-1" role="dialog" aria-labelledby="modal-achievement"
    aria-hidden="true">
    <div class="modal-dialog modal-tertiary modal-dialog-centered" role="document">
        <div class="modal-content"><button type="button" class="btn-close theme-settings-close fs-6 ms-auto"
                data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-header mx-auto">
                <p class="lead mb-0 text-white">Select Option</p>
            </div>
            <div class="modal-body pt-0">
            </div>
            <div class="modal-footer d-flex justify-content-center pt-0 pb-3">
                <a href="{% url 'app1_authentication:logout' %}"><i class="bi bi-x-circle">Logout</i></a>
                <button type="button" class="btn btn-sm btn-white text-tertiary" data-bs-dismiss="modal">New Password</button>
            </div>
        </div>
    </div>
</div>

<!-- raw merials-->
<div class="modal fade" id="raw_metrials" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select Option</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4 col-4">
                    <i class="bi bi-c-square" style="color: DARKRED;"> Copper</i>
                    
                </div>
                <div class="col-md-4 col-4">
                    <i class="bi bi-circle" style="color: rgb(34 68 5);"> PVC  </i>
                </div>
                <div class="col-md-4 col-4">
                    <i class="bi bi-c-square" style="color: DARKRED;"> Copper</i>
                </div>
            </div>
        </div>
    </div>

    </div>
  </div>
</div>

templates/master/nav.html
  {% load static %}
  <nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none"><a class="navbar-brand me-lg-5"
      href="https://demo.themesberg.com/volt-pro/index.html"><img class="navbar-brand-dark"
        src="{% static 'master/assets/img/brand/light.svg'%}" alt="Volt logo"> <img class="navbar-brand-light"
        src="{% static 'master/assets/img/brand/dark.svg'%}" alt="Volt logo"></a>
    <div class="d-flex align-items-center"><button class="navbar-toggler d-lg-none collapsed" type="button"
        data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
        aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button></div>
  </nav>
  <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
      <div class="user-card d-flex d-md-none justify-content-between justify-content-md-center pb-4">
        <div class="d-flex align-items-center">
          <div class="avatar-lg me-4"><img src="{% static 'master/assets/img/team/profile-picture-3.jpg'%}"
              class="card-img-top rounded-circle border-white" alt="Bonnie Green"></div>
          <div class="d-block">
            <h2 class="h5 mb-3">Hi, Jane</h2><a href="../examples/sign-in.html"
              class="btn btn-secondary btn-sm d-inline-flex align-items-center"><svg class="icon icon-xxs me-1"
                fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
              </svg> Sign Out</a>
          </div>
        </div>
        <div class="collapse-close d-md-none"><a href="#sidebarMenu" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
            aria-label="Toggle navigation"><svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                clip-rule="evenodd"></path>
            </svg></a></div>
      </div>
      <ul class="nav flex-column pt-3 pt-md-0">
        <li class="nav-item">
          <a href="https://demo.themesberg.com/volt-pro/index.html" class="nav-link d-flex align-items-center"><span
              class="sidebar-icon"> </span><span class="mt-1 sidebar-text">UniBon ERP</span>
          </a>
        </li>


      <!--master -->
      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
        <li class="nav-item">
          <span class="nav-link d-flex justify-content-between align-items-center"
            data-bs-toggle="collapse" data-bs-target="#master">
            <span>
              <span class="sidebar-icon">
                <i style="color:red;">M</i>
              </span>
              <span class="sidebar-text">Masters

              </span>
            </span>
            <span class="link-arrow">
              <svg
                class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                  clip-rule="evenodd"></path>
              </svg>
            </span>
          </span>
          <div class="multi-level collapse" role="list" id="master" aria-expanded="false">
            <ul class="flex-column nav">
             
              <li class="nav-item">
                <a href="{% url 'app6_master:designation' %}" class="nav-link">
                  <span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text">Designations
                      
                  </span>
                </a>
              </li>

              <li class="nav-item" data-bs-toggle="modal" data-bs-target="#raw_metrials">
                <a href="{% url 'app6_master:item_code' %}" class="nav-link">
                  <span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text"> Item Codes
                      
                  </span>
                </a>
              </li>

              <li class="nav-item" data-bs-toggle="modal" data-bs-target="#raw_metrials">
                <a href="{% url 'app6_master:unit' %}" class="nav-link">
                  <span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text"> Units
                      
                  </span>
                </a>
              </li>

            </ul>
          </div>
        </li>

      <!--Item-->  
        <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
        <li class="nav-item">
          <span class="nav-link d-flex justify-content-between align-items-center"
            data-bs-toggle="collapse" data-bs-target="#Product">
            <span>
              <span class="sidebar-icon">
                 <i style="color:rgb(250, 242, 10);">I</i>
              </span>
              <span class="sidebar-text">Item

              </span>
            </span>
            <span class="link-arrow">
              <svg
                class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                  clip-rule="evenodd"></path>
              </svg>
            </span>
          </span>
          <div class="multi-level collapse" role="list" id="Product" aria-expanded="false">
            <ul class="flex-column nav">
             
              <li class="nav-item">
                <a href="{% url 'app4_product:product_list_create' %}" class="nav-link">
                  <span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text">Product List
                      
                  </span>
                </a>
              </li>

              <li class="nav-item" data-bs-toggle="modal" data-bs-target="#raw_metrials">
                <a class="nav-link">
                  <span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text"> Raw Materials
                      
                  </span>
                </a>
              </li>

            </ul>
          </div>
        </li>

      <!--Employee Manager-->
        <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
        <li class="nav-item">
          <span class="nav-link d-flex justify-content-between align-items-center"
            data-bs-toggle="collapse" data-bs-target="#employee">
            <span>
              <span class="sidebar-icon">
                <i style="color:rgb(11, 245, 30);">E</i>
              </span>
              <span class="sidebar-text">Employee Manager

              </span>
            </span>
            <span class="link-arrow">
              <svg
                class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                  clip-rule="evenodd"></path>
              </svg>
            </span>
          </span>
          <div class="multi-level collapse" role="list" id="employee" aria-expanded="false">
            <ul class="flex-column nav">
             
              <li class="nav-item"><a href="{% url 'app3_employee_management:add_employee' %}" class="nav-link"><span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text">Employee List</span></a></li>

            </ul>
          </div>
        </li>

      <!--User Manager-->
      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
        <li class="nav-item">
          <span class="nav-link d-flex justify-content-between align-items-center"
            data-bs-toggle="collapse" data-bs-target="#submenu-dashboard">
            <span>
              <span class="sidebar-icon">
                <i style="color:rgb(244, 94, 14);">U</i>
              </span>
              <span class="sidebar-text">User Manager

              </span>
            </span>
            <span class="link-arrow">
              <svg
                class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                  clip-rule="evenodd"></path>
              </svg>
            </span>
          </span>
          <div class="multi-level collapse" role="list" id="submenu-dashboard" aria-expanded="false">
            <ul class="flex-column nav">
             
              <li class="nav-item"><a href="{% url 'app1_authentication:user_list' %}" class="nav-link"><span
                    class="sidebar-text-contracted">T</span><span class="sidebar-text">All Users</span></a></li>

            </ul>
          </div>
        </li>

      <!--RMS-->
      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
        <li class="nav-item">
          <a href="{% url 'app7_rms:rms_list_or_create'%}">
            <span class="nav-link d-flex justify-content-between align-items-center"
              data-bs-toggle="collapse" data-bs-target="sds">
              <span>
                <span class="sidebar-icon">
                  <i style="color:rgb(36, 248, 212);">R</i>
                </span>
                <span class="sidebar-text">RMS

                </span>
              </span>
              <span class="link-arrow">
                <svg
                  class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"></path>
                </svg>
              </span>
            </span>
          </a>         
        </li>

      </ul>
    </div>
  </nav>